#!/usr/bin/env python3
"""Collaudo della pagina contro un'istanza di PROVA (mai quella vera):

    PALINSESTO_DATI=<db di prova.py> PALINSESTO_CONF=<conf con utente di prova> \
    PALINSESTO_PROVA=1 PALINSESTO_PORTA=45091 python3 app.py &
    python3 prova_web.py [indirizzo-esterno-per-il-403]

L'utente di prova e' «prova» / «prova-prova-123» / TOTP JBSWY3DPEHPK3PXP:
va creato solo nella conf di prova, mai in ~/.config/palinsesto.
"""
import re, sys, pyotp, requests

B = "http://127.0.0.1:45091"
s = requests.Session()
ERR = []
def ok(nome, cond, extra=""):
    print(("ok   " if cond else "NO   ") + nome + ("" if cond else f"  {extra}"))
    if not cond: ERR.append(nome)

r = s.get(B + "/", allow_redirects=False); ok("senza sessione -> accesso", r.status_code == 302 and "/accesso" in r.headers["Location"], r.status_code)
r = s.post(B + "/accesso", data=dict(nome="prova", password="sbagliata", codice="000000")); ok("password sbagliata -> 401", r.status_code == 401)
r = s.post(B + "/accesso", data=dict(nome="prova", password="prova-prova-123", codice=pyotp.TOTP("JBSWY3DPEHPK3PXP").now(), dopo="/novita"), allow_redirects=False)
ok("accesso giusto -> torna a /novita", r.status_code == 302 and r.headers["Location"].endswith("/novita"), (r.status_code, r.headers.get("Location")))
r = s.post(B + "/accesso", data=dict(nome="prova", password="prova-prova-123", codice="1", dopo="//esterno.example"), allow_redirects=False)
for p in ["/", "/cerca", "/liste", "/liste/1", "/liste/tutti", "/liste/piaciuti", "/liste/avvisi", "/liste/1?da_vedere=1&miei_abb=1&tipo=tv&servizio=1",
          "/novita", "/novita?servizio=1", "/servizio/1", "/servizio/3", "/abbonamenti", "/impostazioni", "/importa", "/t/tv/1", "/t/movie/2", "/static/stile.css"]:
    r = s.get(B + p); ok(f"GET {p} -> {r.status_code}", r.status_code == 200, r.text[-300:])
csrf = re.search(r'name="csrf" value="([^"]+)"', s.get(B + "/t/tv/1").text).group(1)
ok("«Dove lo trovi» porta alla pagina del servizio", 'href="/servizio/' in s.get(B + "/t/tv/1").text)
ok("servizio inesistente -> 404", s.get(B + "/servizio/9999").status_code == 404)
r = s.post(B + "/t/tv/1", data=dict(azione="mi_piace")); ok("POST senza CSRF -> 400", r.status_code == 400)
if "♥ Mi piace" in s.get(B + "/t/tv/1").text:          # prova.py puo' averlo lasciato gia' acceso
    s.post(B + "/t/tv/1", data=dict(azione="mi_piace", csrf=csrf))
r = s.post(B + "/t/tv/1", data=dict(azione="mi_piace", csrf=csrf)); ok("mi piace", r.status_code == 200 and "♥ Mi piace" in r.text)
r = s.post(B + "/t/tv/1", data=dict(azione="stagione", n=3, csrf=csrf)); ok("stagione 3 vista", r.status_code == 200 and r.text.count('aria-pressed="true" title="Vista"') >= 1)
for n in (1, 2, 3):   # nessuna spunta: la prova parte pulita
    r = s.post(B + "/t/tv/1", data=dict(azione="stagione", n=n, csrf=csrf))
ok("nessuna stagione vista", r.text.count('title="Vista"') == 0, r.text.count('title="Vista"'))
ok("tasto: «segna tutte come viste»", "segna tutte come viste" in r.text)
r = s.post(B + "/t/tv/1", data=dict(azione="tutte_viste", csrf=csrf))
ok("segna tutte come viste", r.text.count('title="Vista"') == 2, r.text.count('title="Vista"'))
ok("...e il tasto diventa «segna tutte come da vedere»", "segna tutte come da vedere" in r.text)
r = s.post(B + "/t/tv/1", data=dict(azione="tutte_da_vedere", csrf=csrf))
ok("segna tutte come da vedere", r.text.count('title="Vista"') == 0 and "segna tutte come viste" in r.text)
r = s.post(B + "/t/tv/1", data=dict(azione="tutte_viste", csrf=csrf))
r = s.post(B + "/t/tv/1", data=dict(azione="stagione", n=1, csrf=csrf))
ok("togli la 1: la 2 resta vista", r.text.count('title="Vista"') == 1, r.text.count('title="Vista"'))
ok("la stagione con episodi si apre (details)", 'class="stagione-dettagli"' in s.get(B + "/t/tv/1").text)
r = s.post(B + "/t/tv/1", data=dict(azione="avvisi", csrf=csrf)); ok("avvisi spenti", "Avvisi spenti" in r.text)
r = s.post(B + "/t/tv/1", data=dict(azione="avvisi", csrf=csrf)); ok("avvisi riaccesi", "Avvisi attivi" in r.text)
r = s.post(B + "/t/tv/1", data=dict(azione="boh", csrf=csrf)); ok("azione sconosciuta -> 400", r.status_code == 400)
r = s.post(B + "/liste", data=dict(azione="nuova", nome="Horror", csrf=csrf)); ok("nuova lista", "Horror" in r.text)
if "✓ Da vedere" in s.get(B + "/t/movie/2").text:      # il collaudo non dipende dallo stato lasciato da prova.py
    s.post(B + "/t/movie/2", data=dict(azione="lista", lista=1, csrf=csrf))
r = s.post(B + "/t/movie/2", data=dict(azione="lista", lista=1, csrf=csrf)); ok("film in «Da vedere»", r.status_code == 200 and "✓ Da vedere" in r.text)
r = s.post(B + "/t/movie/2", data=dict(azione="visto", csrf=csrf)); ok("film visto: esce da «Da vedere»", "+ Da vedere" in r.text and "✓ Visto" in r.text)
r = s.get(B + "/liste/visti"); ok("...e compare fra i Visti", "Film Due" in r.text)
r = s.post(B + "/t/movie/2", data=dict(azione="visto", csrf=csrf)); ok("spunta tolta: rientra", "✓ Da vedere" in r.text)
r = s.post(B + "/t/movie/2", data=dict(azione="lista", lista=1, csrf=csrf, torna="//esterno.example"), allow_redirects=False)
ok("«torna» esterno ignorato", r.status_code == 302 and "esterno" not in r.headers["Location"], r.headers.get("Location"))
r = s.post(B + "/abbonamenti/1", data=dict(stato="attivo", ciclo="mese", prezzo="13,99", rinnovo="2026-10-15", csrf=csrf))
ok("salva abbonamento", r.status_code == 200 and "13,99" in r.text)
ok("spesa mensile", "Spesa attuale: <b>13,99 €</b>" in r.text, re.search(r"Spesa attuale.*", r.text))
r = s.post(B + "/abbonamenti/1", data=dict(stato="boh", ciclo="mese", csrf=csrf)); ok("stato non valido -> 400", r.status_code == 400)
r = s.post(B + "/abbonamenti/1", data=dict(stato="attivo", ciclo="mese", rinnovo="ieri", csrf=csrf)); ok("data non valida -> 400", r.status_code == 400)
r = s.post(B + "/impostazioni", data=dict(azione="seguito", servizio=6, csrf=csrf)); ok("smetti di seguire un servizio", r.status_code == 200 and "Non seguito" in r.text)
r = s.post(B + "/impostazioni", data=dict(azione="seguito", servizio=6, csrf=csrf))
r = s.get(B + "/"); ok("home: Conviene? presente", "Conviene?" in r.text and "Netflix" in r.text)
ok("home: consigliati col motivo", "Consigliati per te" in r.text and "Consigliata Netflix" in r.text and "per «Serie Uno»" in r.text)
r = s.get(B + "/"); ok("home: in arrivo sulle piattaforme", "In arrivo sulle piattaforme" in r.text and "Torna con la 2" in r.text and "Netflix · 3" in r.text and "S04E05" in r.text)
r = s.get(B + "/in-arrivo?servizio=1"); ok("pagina in arrivo per Netflix", r.status_code == 200 and "Stagione 2" in r.text and "Nuova serie" in r.text)
ok("pagina servizio: in arrivo su Netflix", "In arrivo su Netflix · 3" in s.get(B + "/servizio/1").text)
ok("pagina in arrivo, tutti", s.get(B + "/in-arrivo").status_code == 200)
ok("pagina servizio: consigliati", "Consigliati per te su Netflix" in s.get(B + "/servizio/1").text)
r = s.post(B + "/consigliati", data=dict(azione="nascondi", titolo="tv:50", csrf=csrf))
ok("«Non mi interessa»: sparisce", r.status_code == 200 and "Consigliata Netflix" not in r.text)
r = s.post(B + "/consigliati", data=dict(azione="nascondi", titolo="tv:999", csrf=csrf)); ok("consiglio inesistente -> 400", r.status_code == 400)
# scheda: liste in alto, «Non mi interessa» per i titoli non miei
r = s.get(B + "/t/tv/62"); ok("scheda non mia: «Non mi interessa» e liste in alto", 'value="nascondi"' in r.text and r.text.index('id="liste"') < r.text.index("Dove lo trovi"))
r = s.post(B + "/t/tv/62", data=dict(azione="nascondi", csrf=csrf)); ok("...premuto: «✕ Non ti interessa»", "✕ Non ti interessa" in r.text)
ok("...e fuori da «In arrivo»", "Originale nuova" not in s.get(B + "/in-arrivo").text)
r = s.post(B + "/t/tv/62", data=dict(azione="nascondi", csrf=csrf)); ok("...ripremuto: torna in gioco", "✕ Non ti interessa" not in r.text and "Originale nuova" in s.get(B + "/in-arrivo").text)
s.post(B + "/t/tv/62", data=dict(azione="nascondi", csrf=csrf))
r = s.post(B + "/t/tv/62", data=dict(azione="lista", lista=1, csrf=csrf)); ok("nascosto messo in lista: non è più nascosto", "✓ Da vedere" in r.text and "Originale nuova" not in s.get(B + "/impostazioni").text.split("Provider TMDB")[0])
ok("...ed è mio: niente «Non mi interessa»", 'value="nascondi"' not in r.text)
r = s.post(B + "/t/tv/62", data=dict(azione="nascondi", csrf=csrf)); ok("nascondere un mio titolo -> 400", r.status_code == 400)
s.post(B + "/t/tv/62", data=dict(azione="rimuovi", csrf=csrf))
r = s.post(B + "/t/tv/62", data=dict(azione="avvisi", csrf=csrf)); ok("«Avvisi spenti» su un titolo non mio: li ACCENDE", "✓ Avvisi attivi" in r.text)
s.post(B + "/t/tv/62", data=dict(azione="rimuovi", csrf=csrf))

# 👍 e 👎 su «In arrivo»
r = s.get(B + "/in-arrivo")
ok("in arrivo: 👍 e 👎 sulle righe non mie", 'value="aggiungi"' in r.text and 'value="nascondi"' in r.text)
ok("...«Potrebbe piacerti» con motivo sulla serie simile ai miei", "Potrebbe piacerti · come «Serie Uno»" in r.text)
ok("...la simile al nascosto in fondo al mese e sbiadita", 'class="riga-arrivo lontano"' in r.text)
ok("...niente tasti sulle mie", 'id="arr-tv-61"' in r.text and 'name="titolo" value="tv:61"' not in r.text)
r = s.post(B + "/consigliati", data=dict(azione="nascondi", titolo="tv:62", torna="/in-arrivo#arr-tv-62", csrf=csrf))
ok("👎: sparisce da «In arrivo»", r.status_code == 200 and "Originale nuova" not in r.text)
r = s.get(B + "/impostazioni"); ok("...e compare fra «Non mi interessano»", "Originale nuova" in r.text and 'value="ripristina"' in r.text)
r = s.post(B + "/consigliati", data=dict(azione="ripristina", titolo="tv:62", torna="/impostazioni", csrf=csrf))
ok("ripristina: esce da «Non mi interessano»", r.status_code == 200 and "Originale nuova" not in r.text)
ok("...e torna fra gli arrivi", "Originale nuova" in s.get(B + "/in-arrivo").text)
r = s.post(B + "/consigliati", data=dict(azione="aggiungi", titolo="tv:60", torna="/in-arrivo?servizio=1#arr-tv-60", csrf=csrf), allow_redirects=False)
ok("👍: torna alla riga", r.status_code == 302 and r.headers["Location"].endswith("/in-arrivo?servizio=1#arr-tv-60"), r.headers.get("Location"))
r = s.get(B + "/in-arrivo?servizio=1"); ok("...ora è «nei tuoi», senza tasti", 'name="titolo" value="tv:60"' not in r.text and "nei tuoi" in r.text)
ok("...ed è in «Da vedere»", "Torna con la 2" in s.get(B + "/liste/1").text)
r = s.post(B + "/consigliati", data=dict(azione="boh", titolo="tv:60", csrf=csrf)); ok("azione sconosciuta -> 400", r.status_code == 400)
r = s.post(B + "/consigliati", data=dict(azione="nascondi", titolo="tv:62")); ok("👎 senza CSRF -> 400", r.status_code == 400)
ok("home: in arrivo con i tasti", 'value="nascondi"' in s.get(B + "/").text)
r = s.get(B + "/piano"); ok("pagina piano", r.status_code == 200 and "Cosa fare adesso" in r.text and "Mese per mese" in r.text, r.text[-300:])
ok("home: link al piano", 'href="/piano"' in s.get(B + "/").text)
r = s.post(B + "/piano", data=dict(ore=12, csrf=csrf)); ok("ore al mese salvate", r.status_code == 200 and 'value="12"' in r.text)
r = s.post(B + "/piano", data=dict(ore=0, csrf=csrf)); ok("ore non valide -> 400", r.status_code == 400)
r = s.post(B + "/piano", data=dict(ore=12)); ok("piano: POST senza CSRF -> 400", r.status_code == 400)
r = s.post(B + "/piano", data=dict(azione="calendario", csrf=csrf)); ok("aggiorna calendario senza conf: la pagina regge", r.status_code == 200 and "Cosa fare adesso" in r.text)
r = s.post(B + "/abbonamenti/1", data=dict(stato="attivo", ciclo="mese", prezzo="13,99", rinnovo="2026-12-15", csrf=csrf))
r = s.post(B + "/abbonamenti/1/fatto", data=dict(azione="disdetto", torna="/abbonamenti", csrf=csrf))
ok("«L'ho disdetto»: disdetto fino al giorno prima del rinnovo", r.status_code == 200 and "Disdetto" in r.text and "14/12/2026" in r.text, re.findall(r"Disdetto[^<]*", r.text)[:2])
r = s.post(B + "/abbonamenti/1/fatto", data=dict(azione="disdetto", csrf=csrf)); ok("disdire un disdetto -> 400", r.status_code == 400)
r = s.post(B + "/abbonamenti/1/fatto", data=dict(azione="attivato", torna="/abbonamenti", csrf=csrf))
ok("«L'ho attivato oggi»: attivo, rinnovo fra un mese", r.status_code == 200 and "Attivo · rinnovo" in r.text, re.findall(r"Attivo[^<]*", r.text)[:2])
r = s.post(B + "/abbonamenti/1", data=dict(stato="disdetto", ciclo="mese", rinnovo="2026-12-15", csrf=csrf))
ok("disdetto senza fine dal modulo: fine = giorno prima del rinnovo", "finisce il 14/12/2026" in r.text or "finito il 14/12/2026" in r.text, re.findall(r"Disdetto[^<]*", r.text)[:2])
r = s.post(B + "/abbonamenti/1", data=dict(stato="pausa", ciclo="mese", pausa_fino="2030-01-15", pausa_proroghe="1", csrf=csrf))
ok("pausa dal modulo", r.status_code == 200 and "In pausa fino al 15/01/2030" in r.text and "proroghe rimaste 1" in r.text, re.findall(r"In pausa[^<]*", r.text)[:2])
r = s.post(B + "/abbonamenti/1", data=dict(stato="pausa", ciclo="mese", csrf=csrf)); ok("pausa senza data -> 400", r.status_code == 400)
r = s.post(B + "/abbonamenti/1/fatto", data=dict(azione="prolungata", fino="2030-04-15", torna="/abbonamenti", csrf=csrf))
ok("pausa prolungata: data nuova, una proroga in meno (ne restano 0)", "In pausa fino al 15/04/2030" in r.text and "proroghe rimaste 0" in r.text, re.findall(r"In pausa[^<]*", r.text)[:2])
r = s.post(B + "/abbonamenti/1", data=dict(stato="pausa", ciclo="mese", pausa_fino="2030-04-15", pausa_proroghe="", csrf=csrf))
r = s.post(B + "/abbonamenti/1/fatto", data=dict(azione="prolungata", fino="2030-07-15", torna="/abbonamenti", csrf=csrf))
ok("proroghe non note: dopo una proroga restano non note", "In pausa fino al 15/07/2030" in r.text and "proroghe rimaste" not in r.text, re.findall(r"In pausa[^<]*", r.text)[:2])
r = s.get(B + "/piano"); ok("piano con un servizio in pausa", r.status_code == 200)
r = s.post(B + "/abbonamenti/1/fatto", data=dict(azione="ripreso", torna="/abbonamenti", csrf=csrf))
ok("ripreso dalla pausa: attivo, rinnovo fra un mese", "Attivo · rinnovo" in r.text and not re.search(r"In pausa fino al \d", r.text))
r = s.post(B + "/abbonamenti/1/fatto", data=dict(azione="pausa", fino="2030-02-01", proroghe="1", torna="/abbonamenti", csrf=csrf))
ok("«L'ho messo in pausa» dal piano: comincia al rinnovo (fra un mese), non oggi", re.search(r"poi in pausa dal \d\d/\d\d/\d{4} al 01/02/2030", r.text) is not None,
   re.findall(r"Attivo fino[^<]*|In pausa[^<]*", r.text)[:2])
r = s.post(B + "/abbonamenti/1/fatto", data=dict(azione="disdetto", torna="/abbonamenti", csrf=csrf))
ok("disdetto con la pausa solo chiesta: resta pagato fino al giorno prima, niente più pausa", "Disdetto" in r.text and "finisce il" in r.text
   and not re.search(r"In pausa fino al \d|poi in pausa dal", r.text), re.findall(r"Disdetto[^<]*", r.text)[:2])
r = s.post(B + "/abbonamenti/9999/fatto", data=dict(azione="attivato", csrf=csrf)); ok("servizio inesistente -> 404", r.status_code == 404)
# «non c'e' davvero» nella scheda, con conferma
r = s.get(B + "/t/tv/1")
m = re.search(r'data-conferma="[^"]*non è davvero su Netflix[^"]*"><input type="hidden" name="csrf" value="[^"]+"><input type="hidden" name="azione" value="non_ce"><input type="hidden" name="servizio" value="(\d+)"', r.text)
ok("scheda: «non c'è davvero» su Netflix, con conferma", bool(m), r.text[r.text.find('id="dove"'):][:400])
if m:
    nf = m.group(1)
    r = s.post(B + "/t/tv/1", data=dict(azione="non_ce", servizio=nf, csrf=csrf))
    ok("...premuto: barrato e «c'è di nuovo»", r.status_code == 200 and "hai segnalato che non c'è" in r.text and "c'è di nuovo" in r.text)
    r = s.post(B + "/t/tv/1", data=dict(azione="ce_di_nuovo", servizio=nf, csrf=csrf))
    ok("...«c'è di nuovo»: torna normale", "hai segnalato che non c'è" not in r.text and 'value="non_ce"' in r.text)
r = s.post(B + "/t/tv/1", data=dict(azione="non_ce", servizio=9999, csrf=csrf)); ok("servizio dove non e' -> 400", r.status_code == 400)
r = s.post(B + "/t/tv/1", data=dict(azione="non_ce", servizio=1)); ok("correzione senza CSRF -> 400", r.status_code == 400)

# pausa: dal rinnovo, annullabile prima che cominci
s.post(B + "/abbonamenti/1", data=dict(stato="attivo", ciclo="mese", prezzo="13,99", rinnovo="2030-01-10", pausa_durate="30, 60,90", csrf=csrf))
r = s.get(B + "/abbonamenti"); ok("durate della pausa salvate", 'value="30, 60, 90"' in r.text)
s.post(B + "/abbonamenti/1", data=dict(stato="attivo", ciclo="mese", prezzo="13,99", rinnovo="2030-01-10", pausa_durate="30 x 3", csrf=csrf))
r = s.get(B + "/abbonamenti"); ok("pausa a passi «30x3» salvata", 'value="30x3"' in r.text)
r = s.post(B + "/abbonamenti/1/fatto", data=dict(azione="pausa", fino="2030-03-10", torna="/abbonamenti", csrf=csrf))
ok("«L'ho messo in pausa»: comincia al rinnovo, fino ad allora attivo", "poi in pausa dal 10/01/2030 al 10/03/2030" in r.text, re.findall(r"Attivo fino[^<]*|In pausa[^<]*", r.text)[:2])
r = s.post(B + "/abbonamenti/1/fatto", data=dict(azione="pausa", fino="2030-04-10", csrf=csrf)); ok("una seconda pausa sopra la prima -> 400", r.status_code == 400)
ok("piano con una pausa programmata", s.get(B + "/piano").status_code == 200)
r = s.post(B + "/abbonamenti/1/fatto", data=dict(azione="ripreso", torna="/abbonamenti", csrf=csrf))
ok("«Ho annullato la pausa»: si rinnova come prima", "Attivo · rinnovo 10/01/2030" in r.text, re.findall(r"Attivo[^<]*", r.text)[:2])
r = s.post(B + "/abbonamenti/1", data=dict(stato="pausa", ciclo="mese", pausa_dal="2030-01-10", pausa_fino="2030-02-10", csrf=csrf))
ok("pausa programmata anche dal modulo", "poi in pausa dal 10/01/2030 al 10/02/2030" in r.text)
r = s.post(B + "/abbonamenti/1", data=dict(stato="pausa", ciclo="mese", pausa_dal="2030-03-10", pausa_fino="2030-02-10", csrf=csrf)); ok("pausa che finisce prima di cominciare -> 400", r.status_code == 400)

# aggiorna adesso: parte in un processo a parte (qui senza chiave TMDB: fallisce subito, e lo dice)
r = s.get(B + "/impostazioni"); ok("impostazioni: «Aggiorna adesso»", 'value="aggiorna"' in r.text and "Ultimo giro concluso" in r.text)
r = s.post(B + "/impostazioni", data=dict(azione="aggiorna", csrf=csrf), allow_redirects=False)
ok("...lanciato, si torna alla sezione", r.status_code == 302 and r.headers["Location"].endswith("#aggiorna"), r.headers.get("Location"))
import time; time.sleep(3)
r = s.get(B + "/impostazioni"); ok("...e la pagina mostra l'esito del giro", "manca la chiave TMDB" in r.text, re.findall(r'<pre class="registro">[^<]*', r.text))
r = s.post(B + "/impostazioni", data=dict(azione="aggiorna")); ok("aggiorna senza CSRF -> 400", r.status_code == 400)

h = s.get(B + "/").headers; ok("CSP e no-store", "default-src 'none'" in h["Content-Security-Policy"] and h["Cache-Control"] == "no-store")
if len(sys.argv) > 1:
    r = requests.get(f"http://{sys.argv[1]}:45091/accesso"); ok("IP non ammesso -> 403", r.status_code == 403, r.status_code)
r = s.get(B + "/img/w92/..%2f..%2fetc%2fpasswd"); ok("percorso immagine malformato -> 404", r.status_code == 404, r.status_code)
r = s.get(B + "/img/w9999/abcdef.jpg"); ok("misura immagine non ammessa -> 404", r.status_code == 404, r.status_code)
r = s.post(B + "/esci", data=dict(csrf=csrf), allow_redirects=False); ok("uscita", r.status_code == 302)
r = s.get(B + "/", allow_redirects=False); ok("dopo l'uscita -> accesso", r.status_code == 302)
print("\nTUTTO OK" if not ERR else f"\n{len(ERR)} CASI SBAGLIATI")
sys.exit(1 if ERR else 0)
